trigger:
  branches:
    include:
      - main
      - feature/*
  paths:
    include:
      - src
      - tests

# defines where the pipeline should run
# a parameter expression cannot be used here, but a variable reference can
pool:
  name: Azure Pipelines

steps:
- checkout: self

- task: PowerShell@2
  name: EnsurePesterVersion
  displayName: 'Ensure Correct Pester Version'
  inputs:
    targetType: 'filePath'
    filePath: '$(Build.SourcesDirectory)/scripts/powershell/Ensure-PesterVersion.ps1'
    pwsh: true

- task: PowerShell@2
  name: RunPowerShellTests
  displayName: 'Run PowerShell Tests'
  inputs:
    targetType: 'filePath'
    filePath: '$(Build.SourcesDirectory)/tests/powershell/Run-Tests.ps1'
    pwsh: true
