parameters:
  - name: vmImage
    displayName: Virtual Machine Image
    type: string
    default: 'ubuntu-latest' # windows-latest, macos-latest
  - name: buildConfiguration
    displayName: Build Configuration
    type: string
    default: 'Release'
    values:
      - 'Debug'
      - 'Release'
  - name: buildPlatform
    displayName: Build Platform
    type: string
    default: 'AnyCPU'
    values:
      - 'AnyCPU'
      - 'x86'
      - 'x64'
      - 'ARM'
  - name: projectName
    displayName: Project Name
    type: string
  - name: targetFramework # When specified, irrelevant tasks will be not be shown in the pipeline.
    displayName: Target Framework
    type: string
    default: 'NotSpecified'
    values:
      - 'NotSpecified'
      - 'DotNet'
      - 'DotNetCore'
      - 'DotNetStandard'
      - 'DotNetFramework'
      - 'MultiTarget'
  - name: dotNetSDKVersion
    displayName: .NET SDK Version
    type: string
    default: ''
  - name: useGlobalJson
    displayName: Use Global JSON
    type: boolean
    default: false
  - name: signAssembly
    displayName: Sign Assembly
    type: boolean
    default: true
  - name: includeSymbols
    displayName: Include Symbols
    type: boolean
    default: true
  - name: symbolPackageFormat
    displayName: Symbol Package Format
    type: string
    default: 'snupkg'
    values:
      - 'symbols.nupkg'
      - 'snupkg'
  - name: noBuildBeforePack
    displayName: No Build Before Pack
    type: boolean
    default: false
  - name: releaseNotes
    displayName: Release Notes
    type: string
    default: ''
  - name: includeAzureDevOpsPush # Push package to an Azure DevOps feed?
    displayName: Include Azure DevOps Push
    type: boolean
    default: true
  - name: azureDevOpsPackageFeed
    displayName: Azure DevOps Package Feed
    type: string
    default: '' # If specified, the default AzureDevOpsPackageFeed global variable will be overwritten.
  - name: includeGitHubPush # Push to GitHub packages?
    displayName: Include GitHub Push
    type: boolean
    default: false
  - name: includeProGetPush # Push packages to ProGet server?
    displayName: Include ProGet Push
    type: boolean
    default: false
  - name: proGetPackageServiceIndex
    displayName: ProGet Package Service Index
    type: string
    default: '' # If specified, the default ProGetPackageServiceIndex global variable will be overwritten.
  - name: runTests
    displayName: Run Tests
    type: boolean
    default: true
  - name: testProjects
    displayName: Test Projects
    type: object
    default: ['*.csproj'] # Allow for providing specific .csproj names in the standard "test"/"tests" folder in the main repo root.
  - name: testMode # Allow for skipping package push steps, symbol publication, etc.
    displayName: Test Mode
    type: boolean
    default: false
  - name: includeLogSteps
    displayName: Include Log Steps
    type: boolean
    default: true

variables:
  - name: VirtualMachineImage
    value: ${{ parameters.vmImage }}
  - name: BuildConfiguration
    value: ${{ parameters.buildConfiguration }}
  - name: BuildPlatform
    value: ${{ parameters.buildPlatform }}
  - name: ProjectName
    value: ${{ parameters.projectName }}
  - name: TargetFramework
    value: ${{ parameters.targetFramework }}
  - name: DotNetSDKVersion
    value: ${{ parameters.dotNetSDKVersion }}
  - name: SignAssembly
    value: ${{ parameters.signAssembly }}
  - name: IncludeSymbols
    value: ${{ parameters.includeSymbols }}
  - name: SymbolPackageFormat
    value: ${{ parameters.symbolPackageFormat }}
  - name: NoBuildBeforePack
    value: ${{ parameters.noBuildBeforePack }}
  - name: ReleaseNotes
    value: ${{ parameters.releaseNotes }}
  - name: RunTests
    value: ${{ parameters.runTests }}
  - name: TestMode
    value: ${{ parameters.testMode }}
  - group: GlobalSecrets # Must be defined as a variable group in the Azure DevOps UI
  - template: '../templates/shared/variables/global-variables.yaml'
  - template: '../templates/create-nuget-package/variables/create-nuget-package-variables.yaml'

jobs:
  - job: createPackage
    displayName: Create NuGet Package
    continueOnError: false
    steps:
      - template: ../templates/create-nuget-package/steps/create-nuget-package-steps.yaml
        parameters:
          targetFramework: ${{ parameters.targetFramework }}
          dotNetSDKVersion: ${{ parameters.dotNetSDKVersion }}
          useGlobalJson: ${{ parameters.useGlobalJson }}
          includeAzureDevOpsPush: ${{ parameters.includeAzureDevOpsPush }}
          azureDevOpsPackageFeed: ${{ parameters.azureDevOpsPackageFeed }}
          includeGitHubPush: ${{ parameters.includeGitHubPush }}
          includeProGetPush: ${{ parameters.includeProGetPush }}
          proGetPackageServiceIndex: ${{ parameters.proGetPackageServiceIndex }}
          testProjects: ${{ parameters.testProjects }}
          includeLogSteps: ${{ parameters.includeLogSteps }}

# TODO: Rename this file exension to the industry standard .yaml over .yml
# This will be a breaking change to all clients, so it may not be worth it.
# All other internal files have been renamed.

# TODO: Eventually we'll want to remove all older .NET framework paths
# It will help simplify and streamline things.