parameters:
  - name: vmImage
    displayName: Virtual Machine Image
    type: string
    default: "ubuntu-latest" # windows-latest, macos-latest
  - name: buildConfiguration
    displayName: Build Configuration
    type: string
    default: "Release"
    values:
      - "Debug"
      - "Release"
  - name: buildPlatform
    displayName: Build Platform
    type: string
    default: "AnyCPU"
    values:
      - "AnyCPU"
      - "x86"
      - "x64"
      - "ARM"
  - name: projectName
    displayName: Project Name
    type: string
  - name: targetFramework
    displayName: Target Framework
    type: string
    default: "DotNet"
    values:
      - "DotNet"
      - "DotNetCore"
      - "DotNetStandard"
      - "DotNetFramework"
  - name: dotNetSdkOptions
    displayName: .NET SDK Options
    type: object
    default:
      sdkVersion: ""
      useGlobalJson: true
  - name: nuGetOptions
    displayName: NuGet Options
    type: object
    default:
      useCache: false
      clearCache: false
  - name: packageOptions
    displayName: Package Options
    type: object
    default:
      signAssembly: true
      includeSymbols: true
      symbolPackageFormat: "snupkg"
      noBuildBeforePack: true
      releaseNotes: ""
      azureDevOpsPush: true
      azureDevOpsFeed: ""
      gitHubPush: false
      proGetPush: false
      proGetServiceIndex: ""
  - name: testOptions
    displayName: Test Options
    type: object
    default:
      runTests: true
      testProjects: ["*.csproj"]
      testsPathPattern: "**/tests*/**"
  - name: includeLogSteps
    displayName: Include Log Steps
    type: boolean
    default: false
  - name: dryRun
    displayName: Dry Run
    type: boolean
    default: false

variables:
  - name: VirtualMachineImage
    value: ${{ parameters.vmImage }}
  - name: BuildConfiguration
    value: ${{ parameters.buildConfiguration }}
  - name: BuildPlatform
    value: ${{ parameters.buildPlatform }}
  - name: ProjectName
    value: ${{ parameters.projectName }}
  - name: TargetFramework
    value: ${{ parameters.targetFramework }}
  - name: SignAssembly
    value: ${{ coalesce(parameters.packageOptions.signAssembly, true) }}
  - name: IncludeSymbols
    value: ${{ coalesce(parameters.packageOptions.includeSymbols, true) }}
  - name: SymbolPackageFormat
    value: ${{ coalesce(parameters.packageOptions.symbolPackageFormat, 'snupkg') }}
  - name: NoBuildBeforePack
    value: ${{ coalesce(parameters.packageOptions.noBuildBeforePack, true) }}
  - name: ReleaseNotes
    value: ${{ coalesce(parameters.packageOptions.releaseNotes, '') }}
  - name: AzureDevOpsPush
    value: ${{ coalesce(parameters.packageOptions.azureDevOpsPush, true) }}
  - name: AzureDevOpsFeed
    value: ${{ coalesce(parameters.packageOptions.azureDevOpsFeed, '') }}
  - name: GitHubPush
    value: ${{ coalesce(parameters.packageOptions.gitHubPush, false) }}
  - name: ProGetPush
    value: ${{ coalesce(parameters.packageOptions.proGetPush, false) }}
  - name: ProGetServiceIndex
    value: ${{ coalesce(parameters.packageOptions.proGetServiceIndex, '') }}
  - name: RunTests
    value: ${{ coalesce(parameters.testOptions.runTests, true) }}
  - name: TestsPathPattern
    value: ${{ coalesce(parameters.testOptions.testsPathPattern, '**/tests*/**') }}
  - name: DryRun
    value: ${{ parameters.dryRun }}

  - group: GlobalSecrets # Must be defined as a variable group in the Azure DevOps UI
  - template: "../templates/shared/variables/global-variables.yaml"
  - template: "../templates/create-nuget-package/variables/create-nuget-package-variables.yaml"

jobs:
  - job: createPackage
    displayName: Create NuGet Package
    continueOnError: false
    steps:
      - template: ../templates/create-nuget-package/steps/create-nuget-package-steps.yaml
        parameters:
          targetFramework: ${{ parameters.targetFramework }}
          dotNetSdkVersion: ${{ coalesce(parameters.dotNetSdkOptions.sdkVersion, '') }}
          useGlobalJson: ${{ coalesce(parameters.dotNetSdkOptions.useGlobalJson, true) }}
          useNuGetCache: ${{ coalesce(parameters.nuGetOptions.useCache, false) }}
          clearNuGetCache: ${{ coalesce(parameters.nuGetOptions.clearCache, false) }}
          includeAzureDevOpsPush: ${{ coalesce(parameters.packageOptions.azureDevOpsPush, true) }}
          azureDevOpsPackageFeed: ${{ coalesce(parameters.packageOptions.azureDevOpsFeed, '') }}
          includeGitHubPush: ${{ coalesce(parameters.packageOptions.gitHubPush, false) }}
          includeProGetPush: ${{ coalesce(parameters.packageOptions.proGetPush, false) }}
          proGetPackageServiceIndex: ${{ coalesce(parameters.packageOptions.proGetServiceIndex, '') }}
          testProjects: ${{ coalesce(parameters.testOptions.testProjects, ['*.csproj']) }}
          includeLogSteps: ${{ coalesce(parameters.includeLogSteps, false) }}

# TODO: Rename this file exension to the industry standard .yaml over .yml
# This will be a breaking change to all clients, so it may not be worth it.
# All other internal files have been renamed.

# TODO: Eventually we'll want to remove all older .NET framework paths
# It will help simplify and streamline things.
