steps:
  - task: MSBuild@1
    name: BuildDotNetFramework
    displayName: Build Project
    condition: succeeded()
    inputs:
      solution: "**/*.sln"
      msbuildArguments: >
        /p:Configuration=$(BuildConfiguration)
        /p:RestoreDuringBuild=false
        /p:OutputPath=bin\$(BuildConfiguration)\
        /p:Platform=$(BuildPlatform)
        /p:SignAssembly=$(SignAssembly)
        /p:AssemblyOriginatorKeyFile="$(DownloadNuGetSigningKey.secureFilePath)"
        /p:Deterministic=true
        /p:DebugType=portable
        /v:Diagnostic
      configuration: $(BuildConfiguration)
      platform: $(BuildPlatform)
