steps:
  - task: DotNetCoreCLI@2
    name: BuildDotNet
    displayName: Build Project
    condition: succeeded()
    inputs:
      command: "build"
      projects: "**/$(ProjectName).csproj"
      arguments: >
        --configuration $(BuildConfiguration)
        --no-restore
        ${{ if eq(variables['SignAssembly'], 'true') }}:
          /p:SignAssembly=${{ variables['SignAssembly'] }}
        ${{ if ne(variables['AssemblyOriginatorKeyFile'], '') }}:
          /p:AssemblyOriginatorKeyFile=${{ variables['AssemblyOriginatorKeyFile'] }}