parameters:
  - name: tool
    displayName: Tool
    type: string
    default: "dotnet"
    values:
      - msbuild
      - dotnet
  - name: solution
    displayName: Solution
    type: string
    default: "**/*.sln"
  - name: projects
    displayName: Projects
    type: string
    default: "**/*.csproj"

steps:
  - ${{ if eq(parameters.tool, 'dotnet') }}:
      - task: DotNetCoreCLI@2
        name: BuildDotNet
        displayName: Build Project (.NET Core/Standard)
        condition: succeeded()
        inputs:
          command: "build"
          projects: ${{ parameters.projects }}
          arguments: >
            --configuration $(BuildConfiguration)
            --no-restore
            /p:SignAssembly=$(SignAssembly)
            /p:AssemblyOriginatorKeyFile=$(AssemblyOriginatorKeyFile)

  - ${{ if eq(parameters.tool, 'msbuild') }}:
      - task: MSBuild@1
        name: BuildDotNetFramework
        displayName: Build Project (.NET Framework)
        condition: succeeded()
        inputs:
          solution: ${{ parameters.solution }}
          msbuildArguments: >
            /p:Configuration=$(BuildConfiguration)
            /p:RestoreDuringBuild=false
            /p:OutputPath=bin\$(BuildConfiguration)\
            /p:Platform=$(BuildPlatform)
            /p:SignAssembly=$(SignAssembly)
            /p:AssemblyOriginatorKeyFile="$(DownloadNuGetSigningKey.secureFilePath)"
            /p:Deterministic=true
            /p:DebugType=portable
            /v:Diagnostic
          configuration: $(BuildConfiguration)
          platform: $(BuildPlatform)
